/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SubmitLazyImport = createFileRoute('/submit')()
const ComponentsLazyImport = createFileRoute('/components')()
const BadgesLazyImport = createFileRoute('/badges')()

// Create/Update Routes

const SubmitLazyRoute = SubmitLazyImport.update({
  path: '/submit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/submit.lazy').then((d) => d.Route))

const ComponentsLazyRoute = ComponentsLazyImport.update({
  path: '/components',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/components.lazy').then((d) => d.Route))

const BadgesLazyRoute = BadgesLazyImport.update({
  path: '/badges',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/badges.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesLazyImport
      parentRoute: typeof rootRoute
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsLazyImport
      parentRoute: typeof rootRoute
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  BadgesLazyRoute,
  ComponentsLazyRoute,
  SubmitLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/badges",
        "/components",
        "/submit"
      ]
    },
    "/badges": {
      "filePath": "badges.lazy.tsx"
    },
    "/components": {
      "filePath": "components.lazy.tsx"
    },
    "/submit": {
      "filePath": "submit.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
